# Generated by Django 2.1.7 on 2019-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
