# Generated by Django 2.1.7 on 2019-03-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190301_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_picture',
            field=models.ImageField(default='restaurant.jpg', upload_to='images/restaurant'),
        ),
    ]
